### ISSUE TITLE
Update to latest spec

### ISSUE THREAD

**Issue by belak** [nhurden/base16-builder-clojure#1]
You use rgbf, but the latest spec refers to these as dec. Also, the slug should come from the filename, not the title.

Those changes and (as far as I can tell) this will get this builder up to speed.

**Comment by nhurden** [comment]
Everything should now be up-to-date.

**Comment by belak** [comment]
Awesome! Might be worth updating the latest version supported in the main repo as well since I added that to the readme so it's easier to find an up-to-date builder.

https://github.com/chriskempson/base16
